### ISSUE TITLE
Failed to download checkpoints: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by navin-hariharan** [drvpn/runpod_serverless_openvoice_worker#1]
![image](https://github.com/user-attachments/assets/33cd28ce-7863-4b43-9e5c-0db405f8a99f)

**Comment by drvpn** [comment]
It seems that the file at https://myshell-public-repo-hosting.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip has been removed.  I will check if I have access to this on a local file.

**Comment by drvpn** [comment]
I have updated app/handler.py to point to an updated URL that works: https://myshell-public-repo-host.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip
